In [117]:
import numpy as np
np.random.seed(42)
def get_data():
    """
    Generates synthetic data for a 2-feature, 2-output linear regression task using NumPy.
    Outputs are:
        y1 = 2*x1 + 3*x2 + 5 + noise1
        y2 = -x1 + 4*x2 + 2 + noise2
    Returns two outputs:
        X: feature matrix of shape (n_samples, 2), containing x1 and x2
        y: target matrix of shape (n_samples, 2), containing y1 and y2 for each sample
    """

    n_samples = 20

    # Generate random integers for x1 and x2
    x1 = np.random.randint(0, 11, size=(n_samples, 1))
    x2 = np.random.randint(0, 11, size=(n_samples, 1))

    # Stack into feature matrix X
    X = np.hstack((x1, x2))

    # Generate noise for each output
    # noise1 = np.random.uniform(-2, 2, size=(n_samples, 1))
    # noise2 = np.random.uniform(-2, 2, size=(n_samples, 1))
# 
    # Compute targets y1 and y2
    y1 = 2 * x1 + 3 * x2 + 5 #+ noise1
    y2 = -1 * x1 + 4 * x2 + 2 #+ noise2

    # Stack targets into (n_samples, 2)
    y = np.hstack((y1, y2))

    return X, y

In [118]:
# X is a list of (x1, x2) pairs, y is a list of (y1, y2) pairs
X, y = get_data() 
print("Shape of X:",X.shape)
print(X[:5])
print("Shape of y:",y.shape)
print(y[:5])
# Refer to this if you don't understand shapes. https://www.geeksforgeeks.org/python/numpy-array-shape/ 

Shape of X: (20, 2)
[[ 6  7]
 [ 3  5]
 [10  1]
 [ 7  4]
 [ 4  0]]
Shape of y: (20, 2)
[[38 24]
 [26 19]
 [28 -4]
 [31 11]
 [13 -2]]


In [119]:
num_features = 2 # we have x1 and x2
num_targets = 2
W = np.random.rand(num_targets, num_features) # ponder over why the shape is (targets, features), and not the other way round
b = np.random.rand(num_targets) # ponder over why its targets here, and not features
n = len(X)



$$\begin{bmatrix} y_1 \\ y_2 \end{bmatrix} = 
\begin{bmatrix} w_{11} & w_{12} \\ w_{21} & w_{22} \end{bmatrix} 
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}
+
\begin{bmatrix} b_1 \\ b_2 \end{bmatrix}$$





$$\begin{align*}

W_{new} &\doteq W_{old} - \alpha \frac{\partial L}{\partial W}\\

&= W_{old} - \alpha \begin{bmatrix}

(\hat{y}_1 - y_1)x_1 & (\hat{y}_1 - y_1)x_2 \\

(\hat{y}_2 - y_2)x_1 & (\hat{y}_2 - y_2)x_2

\end{bmatrix}
\end{align*}$$
Let $e_1 = \hat{y}_1 - y_1$ and $e_2 = \hat{y}_2 - y_2$

$$\begin{align*} &= \begin{bmatrix} e_1 x_1 & e_1 x_2 \\ e_2 x_1 & e_2 x_2 \end{bmatrix} \\
&= \begin{bmatrix} e_1 \\ e_2 \end{bmatrix} \begin{bmatrix} x_1 & x_2 \end{bmatrix} \end{align*}$$
p.s.$$(WX)^T = X^T W^T$$you'll need it

Note that the shape of X is (20,2), which means that it's a **row** vector

In [ ]:
# Let's apply the update, with alpha = 0.1
alpha = 0.01
for i in range(10_000):
    y_pred = 
    error = y_pred - y # Use this opportunity to check your shape. THIS IS NOT MSE

    
    W -=        # Keep in mind that we have to average the jacobian matrix across all samples
    b -=        # Same as above
    # if you do not average, your weights/bias will explode, and become very large

print("W")
display(W)
print("b")
display(b)

In [129]:
assert np.allclose(W.round(2), np.array([[2, 3], [-1, 4]]))
assert np.allclose(b.round(2), np.array([5, 2]))

In [ ]:
# Let's apply the update once, with alpha = 0.1
alpha = 0.01
for i in range(10_000):
    
    y_pred = X @ W.T + b
    error = y_pred - y # THIS IS NOT MSE
    W -= alpha / n  * error.T @ X
    b -= alpha  * error.mean(axis=0)
print("W")
display(W)
print("b")
display(b)

W


array([[ 2.00020596,  3.0001072 ],
       [-0.99990721,  4.0000483 ]])

b


array([4.99799223, 1.99909544])