In [1]:
import numpy as np

In [11]:
arr = np.r_[np.ones(5)]

In [12]:
arr

array([1., 1., 1., 1., 1.])

In [13]:
mask = arr == 0
mask

array([False, False, False, False, False])

In [14]:
arr[mask]

array([], dtype=float64)

In [15]:
np.argmax(arr[mask])

ValueError: attempt to get argmax of an empty sequence

In [16]:
x = lambda :5

In [18]:
x()

5

In [21]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
np.linspace(0,29,30)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [29]:
arr.ndim

1

In [ ]:
&