In [2]:
import torch


In [ ]:
no_runs = 10
no_planning_steps = 5
no_states = 50
no_actions = 4

runs =  torch.arange(no_runs)
planning =  torch.arange(no_planning_steps)
states = torch.randint(no_states, (no_runs,), dtype=torch.long)
actions = torch.ones(no_runs, dtype=torch.long)

In [ ]:
a = torch.zeros([no_runs,no_states, no_actions])

display(a.shape)
display(a[runs, states, actions].shape)

torch.Size([10, 50, 4, 2])

torch.Size([10, 2])

In [54]:
no_runs = 10
no_planning_steps = 5
no_states = 50
no_actions = 4


model = torch.zeros([no_runs,no_planning_steps,no_states, no_actions,2 ])
model.shape

display(model.shape)
model[runs].shape

torch.Size([10, 5, 50, 4, 2])

torch.Size([10, 5, 50, 4, 2])

In [57]:
runs

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
runs[:]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
runs[:,None]

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [65]:
runs.reshape(-1,1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [3]:
a = torch.arange(5)
a

tensor([0, 1, 2, 3, 4])

In [6]:
a.view(1, 5, 1)

tensor([[[0],
         [1],
         [2],
         [3],
         [4]]])

In [3]:

algorithms = {"DynaQ" : "A", 
              "DynaQ_plus" : "A", 
              "DynaQ_plus_action_bonus" : "A", 
              "DynaQ_plus_selective_sample" : "A"}

for key , value in algorithms.items():
    print(key)

DynaQ
DynaQ_plus
DynaQ_plus_action_bonus
DynaQ_plus_selective_sample
